name: fyp_v101
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  percent_indicator: ^3.4.0
  fl_chart: ^0.67.0
  flutter_advanced_switch: ^3.1.0
  flutter_local_notifications: ^17.0.0
  http: ^1.2.1
  firebase_auth: ^4.19.1
  firebase_core: ^2.29.0
  cloud_firestore: ^4.16.1
  get_cli: ^1.8.1
  home_widget:
  davinci: ^2.0.0
  path_provider:

  get: 4.6.6
  flutter: 
    sdk: flutter
  nb_utils: ^7.0.0
  flutter_screenutil: ^5.9.0
  change_app_package_name: ^1.1.0
  url_launcher: ^6.2.6


dev_dependencies: 
  hive_generator: ^1.1.3
  build_runner: ^2.1.11
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - imgs/
  uses-material-design: true

